version: '3.7'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./data/webapp:/data/webapp"
      - "./data/weblogs:/weblogs"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - docker-network
    depends_on:
      - php


  # 新框架的php配置
  php:
    image: php7.2
    volumes:
      - "./data/webapp:/data/webapp"
      - "./data/weblogs:/weblogs"
      - "./php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini"
    networks:
      - docker-network

  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_SSL_CACERTFILE: /rootCA.pem
      RABBITMQ_SSL_CERTFILE: /rootCA.pem
      RABBITMQ_SSL_KEYFILE: /rootCA.key
      RABBITMQ_SSL_VERIFY: verify_none
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "false"
    volumes:
      - "./tests/files/rootCA.pem:/rootCA.pem:ro"
      - "./tests/files/rootCA.key:/rootCA.key:ro"
    ports:
      - 5671:5671
      - 5672:5672

networks:
    docker-network:
        driver: bridge
