version: "2.2"

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./data/webapp:/data/webapp"
      - "./data/weblogs:/weblogs"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - docker-network
    depends_on:
      - php


  # 新框架的php配置
  php:
    image: php7.2
    volumes:
      - "./data/webapp:/data/webapp"
      - "./data/weblogs:/weblogs"
      - "./php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini"
    networks:
      - docker-network

networks:
    docker-network:
        driver: bridge
