version: '3.7'

services:

  #添加elk
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    # mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports: 
      - "9200:9200"
    volumes: # Directory mount 目录挂载
      - ../data/esdata1:/usr/share/elasticsearch/data
    networks:
      - docker-network

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.1
    container_name: kibana551
    hostname: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - "5601:5601"
    networks:
      - docker-network

  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.1
    container_name: logstash551
    hostname: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ../logstash/conf.d:/etc/logstash/conf.d
      - ../data/weblogs:/weblogs
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "7001-7005:7001-7005"
      - "4567:4567"
    networks:
      - docker-network


networks:
    docker-network:
        driver: bridge # Bridge mode nginx can be used to represent php services IP address in nginx configuration 桥接模式 在nginx的配置中就能使用 php 来代表php的IP地址